# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/morgan/src/mipalgu/zybo_pl_base/zybo_pl_base.srcs/sources_1/bd/design_1/ip/design_1_PmodCAN_0_0/design_1_PmodCAN_0_0.xci
# IP: The module: 'design_1_PmodCAN_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: /home/morgan/src/mipalgu/zybo_pl_base/zybo_pl_base.gen/sources_1/bd/design_1/ip/design_1_PmodCAN_0_0/src/PmodCAN_axi_gpio_0_0/PmodCAN_axi_gpio_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==PmodCAN_axi_gpio_0_0 || ORIG_REF_NAME==PmodCAN_axi_gpio_0_0} -quiet] -quiet

# IP: /home/morgan/src/mipalgu/zybo_pl_base/zybo_pl_base.gen/sources_1/bd/design_1/ip/design_1_PmodCAN_0_0/src/PmodCAN_axi_quad_spi_0_0/PmodCAN_axi_quad_spi_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==PmodCAN_axi_quad_spi_0_0 || ORIG_REF_NAME==PmodCAN_axi_quad_spi_0_0} -quiet] -quiet

# IP: /home/morgan/src/mipalgu/zybo_pl_base/zybo_pl_base.gen/sources_1/bd/design_1/ip/design_1_PmodCAN_0_0/src/PmodCAN_pmod_bridge_0_0/PmodCAN_pmod_bridge_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==PmodCAN_pmod_bridge_0_0 || ORIG_REF_NAME==PmodCAN_pmod_bridge_0_0} -quiet] -quiet

# XDC: /home/morgan/src/mipalgu/zybo_pl_base/zybo_pl_base.gen/sources_1/bd/design_1/ip/design_1_PmodCAN_0_0/src/PmodCAN_axi_gpio_0_0/PmodCAN_axi_gpio_0_0_board.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==PmodCAN_axi_gpio_0_0 || ORIG_REF_NAME==PmodCAN_axi_gpio_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: /home/morgan/src/mipalgu/zybo_pl_base/zybo_pl_base.gen/sources_1/bd/design_1/ip/design_1_PmodCAN_0_0/src/PmodCAN_axi_gpio_0_0/PmodCAN_axi_gpio_0_0_ooc.xdc

# XDC: /home/morgan/src/mipalgu/zybo_pl_base/zybo_pl_base.gen/sources_1/bd/design_1/ip/design_1_PmodCAN_0_0/src/PmodCAN_axi_gpio_0_0/PmodCAN_axi_gpio_0_0.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==PmodCAN_axi_gpio_0_0 || ORIG_REF_NAME==PmodCAN_axi_gpio_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: /home/morgan/src/mipalgu/zybo_pl_base/zybo_pl_base.gen/sources_1/bd/design_1/ip/design_1_PmodCAN_0_0/src/PmodCAN_axi_quad_spi_0_0/PmodCAN_axi_quad_spi_0_0_board.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==PmodCAN_axi_quad_spi_0_0 || ORIG_REF_NAME==PmodCAN_axi_quad_spi_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: /home/morgan/src/mipalgu/zybo_pl_base/zybo_pl_base.gen/sources_1/bd/design_1/ip/design_1_PmodCAN_0_0/src/PmodCAN_axi_quad_spi_0_0/PmodCAN_axi_quad_spi_0_0.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==PmodCAN_axi_quad_spi_0_0 || ORIG_REF_NAME==PmodCAN_axi_quad_spi_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: /home/morgan/src/mipalgu/zybo_pl_base/zybo_pl_base.gen/sources_1/bd/design_1/ip/design_1_PmodCAN_0_0/src/PmodCAN_axi_quad_spi_0_0/PmodCAN_axi_quad_spi_0_0_ooc.xdc

# XDC: /home/morgan/src/mipalgu/zybo_pl_base/zybo_pl_base.gen/sources_1/bd/design_1/ip/design_1_PmodCAN_0_0/src/PmodCAN_axi_quad_spi_0_0/PmodCAN_axi_quad_spi_0_0_clocks.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==PmodCAN_axi_quad_spi_0_0 || ORIG_REF_NAME==PmodCAN_axi_quad_spi_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: /home/morgan/src/mipalgu/zybo_pl_base/zybo_pl_base.gen/sources_1/bd/design_1/ip/design_1_PmodCAN_0_0/src/PmodCAN_pmod_bridge_0_0/PmodCAN_pmod_bridge_0_0_board.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==PmodCAN_pmod_bridge_0_0 || ORIG_REF_NAME==PmodCAN_pmod_bridge_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /home/morgan/src/mipalgu/zybo_pl_base/zybo_pl_base.gen/sources_1/bd/design_1/ip/design_1_PmodCAN_0_0/src/PmodCAN_pmod_bridge_0_0/src/pmod_concat_ooc.xdc

# XDC: /home/morgan/src/mipalgu/zybo_pl_base/zybo_pl_base.gen/sources_1/bd/design_1/ip/design_1_PmodCAN_0_0/design_1_PmodCAN_0_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_PmodCAN_0_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: /home/morgan/src/mipalgu/zybo_pl_base/zybo_pl_base.gen/sources_1/bd/design_1/ip/design_1_PmodCAN_0_0/src/PmodCAN_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_PmodCAN_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: /home/morgan/src/mipalgu/zybo_pl_base/zybo_pl_base.srcs/sources_1/bd/design_1/ip/design_1_PmodCAN_0_0/design_1_PmodCAN_0_0.xci
# IP: The module: 'design_1_PmodCAN_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: /home/morgan/src/mipalgu/zybo_pl_base/zybo_pl_base.gen/sources_1/bd/design_1/ip/design_1_PmodCAN_0_0/src/PmodCAN_axi_gpio_0_0/PmodCAN_axi_gpio_0_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==PmodCAN_axi_gpio_0_0 || ORIG_REF_NAME==PmodCAN_axi_gpio_0_0} -quiet] -quiet

# IP: /home/morgan/src/mipalgu/zybo_pl_base/zybo_pl_base.gen/sources_1/bd/design_1/ip/design_1_PmodCAN_0_0/src/PmodCAN_axi_quad_spi_0_0/PmodCAN_axi_quad_spi_0_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==PmodCAN_axi_quad_spi_0_0 || ORIG_REF_NAME==PmodCAN_axi_quad_spi_0_0} -quiet] -quiet

# IP: /home/morgan/src/mipalgu/zybo_pl_base/zybo_pl_base.gen/sources_1/bd/design_1/ip/design_1_PmodCAN_0_0/src/PmodCAN_pmod_bridge_0_0/PmodCAN_pmod_bridge_0_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==PmodCAN_pmod_bridge_0_0 || ORIG_REF_NAME==PmodCAN_pmod_bridge_0_0} -quiet] -quiet

# XDC: /home/morgan/src/mipalgu/zybo_pl_base/zybo_pl_base.gen/sources_1/bd/design_1/ip/design_1_PmodCAN_0_0/src/PmodCAN_axi_gpio_0_0/PmodCAN_axi_gpio_0_0_board.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==PmodCAN_axi_gpio_0_0 || ORIG_REF_NAME==PmodCAN_axi_gpio_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: /home/morgan/src/mipalgu/zybo_pl_base/zybo_pl_base.gen/sources_1/bd/design_1/ip/design_1_PmodCAN_0_0/src/PmodCAN_axi_gpio_0_0/PmodCAN_axi_gpio_0_0_ooc.xdc

# XDC: /home/morgan/src/mipalgu/zybo_pl_base/zybo_pl_base.gen/sources_1/bd/design_1/ip/design_1_PmodCAN_0_0/src/PmodCAN_axi_gpio_0_0/PmodCAN_axi_gpio_0_0.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==PmodCAN_axi_gpio_0_0 || ORIG_REF_NAME==PmodCAN_axi_gpio_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: /home/morgan/src/mipalgu/zybo_pl_base/zybo_pl_base.gen/sources_1/bd/design_1/ip/design_1_PmodCAN_0_0/src/PmodCAN_axi_quad_spi_0_0/PmodCAN_axi_quad_spi_0_0_board.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==PmodCAN_axi_quad_spi_0_0 || ORIG_REF_NAME==PmodCAN_axi_quad_spi_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: /home/morgan/src/mipalgu/zybo_pl_base/zybo_pl_base.gen/sources_1/bd/design_1/ip/design_1_PmodCAN_0_0/src/PmodCAN_axi_quad_spi_0_0/PmodCAN_axi_quad_spi_0_0.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==PmodCAN_axi_quad_spi_0_0 || ORIG_REF_NAME==PmodCAN_axi_quad_spi_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: /home/morgan/src/mipalgu/zybo_pl_base/zybo_pl_base.gen/sources_1/bd/design_1/ip/design_1_PmodCAN_0_0/src/PmodCAN_axi_quad_spi_0_0/PmodCAN_axi_quad_spi_0_0_ooc.xdc

# XDC: /home/morgan/src/mipalgu/zybo_pl_base/zybo_pl_base.gen/sources_1/bd/design_1/ip/design_1_PmodCAN_0_0/src/PmodCAN_axi_quad_spi_0_0/PmodCAN_axi_quad_spi_0_0_clocks.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==PmodCAN_axi_quad_spi_0_0 || ORIG_REF_NAME==PmodCAN_axi_quad_spi_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: /home/morgan/src/mipalgu/zybo_pl_base/zybo_pl_base.gen/sources_1/bd/design_1/ip/design_1_PmodCAN_0_0/src/PmodCAN_pmod_bridge_0_0/PmodCAN_pmod_bridge_0_0_board.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==PmodCAN_pmod_bridge_0_0 || ORIG_REF_NAME==PmodCAN_pmod_bridge_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /home/morgan/src/mipalgu/zybo_pl_base/zybo_pl_base.gen/sources_1/bd/design_1/ip/design_1_PmodCAN_0_0/src/PmodCAN_pmod_bridge_0_0/src/pmod_concat_ooc.xdc

# XDC: /home/morgan/src/mipalgu/zybo_pl_base/zybo_pl_base.gen/sources_1/bd/design_1/ip/design_1_PmodCAN_0_0/design_1_PmodCAN_0_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_PmodCAN_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: /home/morgan/src/mipalgu/zybo_pl_base/zybo_pl_base.gen/sources_1/bd/design_1/ip/design_1_PmodCAN_0_0/src/PmodCAN_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_PmodCAN_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
